import 'package:pdf/pdf.dart';
import 'package:flutter/material.dart' as material;

/// PDF Template Configuration
/// 
/// Customize your report template by modifying the values in this class
/// or by creating a custom template file
class PdfTemplateConfig {
  // ========== HEADER CONFIGURATION ==========
  
  /// Report title text
  static String reportTitle = 'Attendance Report';
  
  /// Institute name (leave empty to auto-detect from institute data)
  static String? instituteName;
  
  /// Logo image path (optional - can be asset path or URL)
  static String? logoPath;
  
  /// Header background color
  static PdfColor headerBackgroundColor = PdfColors.blue700;
  
  /// Header text color
  static PdfColor headerTextColor = PdfColors.white;
  
  /// Header font size
  static double headerFontSize = 24.0;
  
  // ========== BODY CONFIGURATION ==========
  
  /// Body text color
  static PdfColor bodyTextColor = PdfColors.black;
  
  /// Body font size
  static double bodyFontSize = 10.0;
  
  /// Table header background color
  static PdfColor tableHeaderBackgroundColor = PdfColors.grey200;
  
  /// Table header text color
  static PdfColor tableHeaderTextColor = PdfColors.black;
  
  /// Table border color
  static PdfColor tableBorderColor = PdfColors.grey300;
  
  /// Row alternate background color (for better readability)
  static PdfColor? rowAlternateColor = PdfColors.grey100;
  
  // ========== STATISTICS COLORS ==========
  
  /// Present/Good attendance color
  static PdfColor presentColor = PdfColors.green700;
  
  /// Absent/Poor attendance color
  static PdfColor absentColor = PdfColors.red700;
  
  /// Warning/Medium attendance color
  static PdfColor warningColor = PdfColors.orange700;
  
  /// Primary accent color
  static PdfColor primaryColor = PdfColors.blue700;
  
  /// Accent color (for highlights, totals, etc.)
  static PdfColor accentColor = PdfColors.blue700;
  
  // ========== LAYOUT CONFIGURATION ==========
  
  /// Page margins (all sides)
  static double pageMargin = 40.0;
  
  /// Spacing between sections
  static double sectionSpacing = 20.0;
  
  /// Table cell padding
  static double tableCellPadding = 8.0;
  
  /// Border radius for containers
  static double borderRadius = 8.0;
  
  // ========== CONTENT CONFIGURATION ==========
  
  /// Show student photos in individual reports
  static bool showStudentPhotos = true;
  
  /// Show subject-wise breakdown
  static bool showSubjectBreakdown = true;
  
  /// Show daily attendance details
  static bool showDailyDetails = true;
  
  /// Show statistics summary
  static bool showStatisticsSummary = true;
  
  /// Show entry/exit times
  static bool showEntryExitTimes = true;
  
  /// Show total hours
  static bool showTotalHours = true;
  
  /// Show attendance percentage
  static bool showAttendancePercentage = true;
  
  /// Minimum attendance percentage for "good" status (default: 75%)
  static double goodAttendanceThreshold = 75.0;
  
  // ========== FOOTER CONFIGURATION ==========
  
  /// Show footer
  static bool showFooter = true;
  
  /// Footer text
  static String footerText = 'Generated by Attendance Management System';
  
  /// Footer text color
  static PdfColor footerTextColor = PdfColors.grey600;
  
  /// Footer font size
  static double footerFontSize = 10.0;
  
  // ========== CUSTOM FIELDS ==========
  
  /// Additional custom fields to include in report
  /// Format: {'fieldName': 'Display Label'}
  static Map<String, String> customFields = {};
  
  /// Custom header HTML/text (if you want to use HTML-like formatting)
  static String? customHeaderHtml;
  
  /// Custom footer HTML/text
  static String? customFooterHtml;
  
  // ========== TEMPLATE METHODS ==========
  
  /// Load template from JSON file
  /// You can create a JSON file with your template configuration
  static Future<void> loadFromJson(String jsonPath) async {
    // TODO: Implement JSON loading
    // This allows you to load template from a file
  }
  
  /// Load template from Firestore
  /// Store your template configuration in Firestore
  static Future<void> loadFromFirestore(String instituteId) async {
    // TODO: Implement Firestore loading
    // This allows you to store templates per institute
  }
  
  /// Reset to default template
  static void resetToDefault() {
    reportTitle = 'Attendance Report';
    instituteName = null;
    logoPath = null;
    headerBackgroundColor = PdfColors.blue700;
    headerTextColor = PdfColors.white;
    headerFontSize = 24.0;
    bodyTextColor = PdfColors.black;
    bodyFontSize = 10.0;
    tableHeaderBackgroundColor = PdfColors.grey200;
    tableHeaderTextColor = PdfColors.black;
    tableBorderColor = PdfColors.grey300;
    rowAlternateColor = PdfColors.grey100;
    presentColor = PdfColors.green700;
    absentColor = PdfColors.red700;
    warningColor = PdfColors.orange700;
    primaryColor = PdfColors.blue700;
    pageMargin = 40.0;
    sectionSpacing = 20.0;
    tableCellPadding = 8.0;
    borderRadius = 8.0;
    showStudentPhotos = true;
    showSubjectBreakdown = true;
    showDailyDetails = true;
    showStatisticsSummary = true;
    showEntryExitTimes = true;
    showTotalHours = true;
    showAttendancePercentage = true;
    goodAttendanceThreshold = 75.0;
    showFooter = true;
    footerText = 'Generated by Attendance Management System';
    footerTextColor = PdfColors.grey600;
    footerFontSize = 10.0;
    customFields = {};
    customHeaderHtml = null;
    customFooterHtml = null;
  }
  
  /// Export current template to JSON
  /// This allows you to save your template configuration
  static Map<String, dynamic> toJson() {
    return {
      'reportTitle': reportTitle,
      'instituteName': instituteName,
      'logoPath': logoPath,
      'headerBackgroundColor': null, // Color serialization removed - use default colors
      'headerTextColor': null, // Color serialization removed - use default colors
      'headerFontSize': headerFontSize,
      'bodyTextColor': null, // Color serialization removed - use default colors
      'bodyFontSize': bodyFontSize,
      'tableHeaderBackgroundColor': null, // Color serialization removed
      'tableHeaderTextColor': null, // Color serialization removed
      'tableBorderColor': null, // Color serialization removed
      'presentColor': null, // Color serialization removed
      'absentColor': null, // Color serialization removed
      'warningColor': null, // Color serialization removed
      'primaryColor': null, // Color serialization removed
      'pageMargin': pageMargin,
      'sectionSpacing': sectionSpacing,
      'tableCellPadding': tableCellPadding,
      'borderRadius': borderRadius,
      'showStudentPhotos': showStudentPhotos,
      'showSubjectBreakdown': showSubjectBreakdown,
      'showDailyDetails': showDailyDetails,
      'showStatisticsSummary': showStatisticsSummary,
      'showEntryExitTimes': showEntryExitTimes,
      'showTotalHours': showTotalHours,
      'showAttendancePercentage': showAttendancePercentage,
      'goodAttendanceThreshold': goodAttendanceThreshold,
      'showFooter': showFooter,
      'footerText': footerText,
      'footerTextColor': null, // Color serialization removed - use default colors
      'footerFontSize': footerFontSize,
      'customFields': customFields,
      'customHeaderHtml': customHeaderHtml,
      'customFooterHtml': customFooterHtml,
    };
  }
  
  /// Load template from JSON map
  static void fromJson(Map<String, dynamic> json) {
    reportTitle = json['reportTitle'] ?? 'Attendance Report';
    instituteName = json['instituteName'];
    logoPath = json['logoPath'];
    
    // Color deserialization removed - using default colors
    // Colors can be customized directly in the PdfTemplateConfig class
    
    headerFontSize = json['headerFontSize']?.toDouble() ?? 24.0;
    bodyFontSize = json['bodyFontSize']?.toDouble() ?? 10.0;
    pageMargin = json['pageMargin']?.toDouble() ?? 40.0;
    sectionSpacing = json['sectionSpacing']?.toDouble() ?? 20.0;
    tableCellPadding = json['tableCellPadding']?.toDouble() ?? 8.0;
    borderRadius = json['borderRadius']?.toDouble() ?? 8.0;
    
    showStudentPhotos = json['showStudentPhotos'] ?? true;
    showSubjectBreakdown = json['showSubjectBreakdown'] ?? true;
    showDailyDetails = json['showDailyDetails'] ?? true;
    showStatisticsSummary = json['showStatisticsSummary'] ?? true;
    showEntryExitTimes = json['showEntryExitTimes'] ?? true;
    showTotalHours = json['showTotalHours'] ?? true;
    showAttendancePercentage = json['showAttendancePercentage'] ?? true;
    goodAttendanceThreshold = json['goodAttendanceThreshold']?.toDouble() ?? 75.0;
    showFooter = json['showFooter'] ?? true;
    footerText = json['footerText'] ?? 'Generated by Attendance Management System';
    footerFontSize = json['footerFontSize']?.toDouble() ?? 10.0;
    
    customFields = Map<String, String>.from(json['customFields'] ?? {});
    customHeaderHtml = json['customHeaderHtml'];
    customFooterHtml = json['customFooterHtml'];
  }
}
